[repository]
name = "hyprsnap"
authors = ["elviosak"]
commit_pins = [
#    ["882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff", ""]  # 0.47.2
]

[hyprsnap]
description = "A plugin to add aerosnap functionality to floating windows."
authors = ["elviosak"]
output = "hyprsnap/hyprsnap.so"
build = [
    "make -C hyprsnap all",
]
